# -*- coding: utf-8 -*-
"""preprocess_and_extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkgjkPJxIR0UjNmfvxVugCW6BKzYqHHJ

# Pitt Corpus — Audio Preprocessing + Feature Extraction

**Pipeline overview**
```
Google Drive MP3 files
        ↓
  CELL 1 — Mount Drive + Install packages
        ↓
  CELL 2 — Preprocessing
           Decode MP3 → Noise reduction → Edge trim (pauses preserved)
           → Normalise → Save WAV + audio_manifest.csv
        ↓
  CELL 3 — Feature Extraction
           Group A: Prosodic (18)
           Group B: MFCC + Spectral (189)
           Group C: Pause (8)
           Group D: Voice Quality / Praat (6)
           Group E: Articulation / Formants (10)
           Group F: Temporal Dynamics (8)
           Group G: Disfluency proxies (4)
           Group H: Wav2Vec2 embeddings (768)
           → Save .npz per subject + feature_manifest.csv
        ↓
  CELL 4 — Verify outputs + summary stats
```

**Dataset path expected:**
```
/content/drive/MyDrive/pitt_corpus/
    Dementia/
        *.mp3
    Control/
        *.mp3
```

## Cell 1 — Mount Google Drive + Install Packages
"""

# ── Mount Google Drive ────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

import os
# Verify dataset is accessible
DATASET_PATH = '/content/drive/MyDrive/pitt_corpus'
for cls in ['Dementia', 'Control']:
    folder = os.path.join(DATASET_PATH, cls)
    if os.path.exists(folder):
        n = len([f for f in os.listdir(folder) if f.endswith('.mp3')])
        print(f'  {cls}: {n} .mp3 files found')
    else:
        print(f'  WARNING: {folder} not found — check your Drive path')

# ── Install packages ──────────────────────────────────────────────────────────
# This takes ~2-3 minutes on first run
!pip install -q librosa soundfile pydub noisereduce praat-parselmouth \
                transformers torchaudio tqdm
!apt-get install -qq ffmpeg
print('All packages installed.')

"""## Cell 2 — Preprocessing
Converts raw `.mp3` → clean 16 kHz mono `.wav`  
Internal pauses are **preserved** (they are a primary AD biomarker).  
Only leading/trailing edge silence is removed.
"""

import warnings, logging
warnings.filterwarnings('ignore')
logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)-8s | %(message)s', datefmt='%H:%M:%S')
log = logging.getLogger(__name__)

from pathlib import Path
import numpy as np
import pandas as pd
import librosa
import soundfile as sf
import noisereduce as nr
from pydub import AudioSegment
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

# ── Paths ─────────────────────────────────────────────────────────────────────
INPUT_DIR    = Path('/content/drive/MyDrive/pitt_corpus/audio')
OUTPUT_DIR   = Path('/content/processed_audio')   # Colab local disk (faster I/O)
MANIFEST_OUT = Path('/content/audio_manifest.csv')

# ── Config ────────────────────────────────────────────────────────────────────
SAMPLE_RATE      = 16_000   # Hz — hard requirement for Wav2Vec 2.0
TEST_SIZE        = 0.20     # 80/20 stratified split
RANDOM_STATE     = 42
EDGE_TRIM_TOP_DB = 30       # dB threshold for edge silence detection only
NOISE_PROFILE_S  = 0.5      # seconds used as noise profile for spectral subtraction
MIN_DURATION_S   = 2.0      # discard files shorter than this after trimming
LABEL_MAP        = {'Dementia': 1, 'Control': 0}

# ── Step 1: Discover files ────────────────────────────────────────────────────
def discover_files(input_dir):
    records = []
    for label_str in LABEL_MAP:
        folder = input_dir / label_str
        if not folder.exists():
            log.warning('Folder not found: %s', folder)
            continue
        for mp3 in sorted(folder.glob('*.mp3')):
            records.append({
                'subject_id': mp3.stem,
                'raw_path':   str(mp3),
                'label_str':  label_str,
                'label':      LABEL_MAP[label_str],
            })
    df = pd.DataFrame(records)
    # Modified line: Check if 'label' column exists before summing
    if 'label' in df.columns:
        log.info('Found %d files  (Dementia=%d  Control=%d)',
                 len(df), (df.label==1).sum(), (df.label==0).sum())
    else:
        # If no files found, df is empty and 'label' column doesn't exist
        log.info('Found %d files. No MP3 files found in specified directories.', len(df))
    return df

# ── Step 2: Stratified split ──────────────────────────────────────────────────
def stratified_split(df):
    # Added check for empty DataFrame before splitting
    if df.empty:
        log.info('DataFrame is empty, skipping stratified split.')
        # Return a DataFrame with 'split' column to avoid downstream errors, even if empty
        return pd.DataFrame(columns=df.columns.tolist() + ['split'])

    _, test_df = train_test_split(
        df, test_size=TEST_SIZE,
        stratify=df['label'],
        random_state=RANDOM_STATE,
    )
    df = df.copy()
    df['split'] = 'train'
    df.loc[test_df.index, 'split'] = 'test'
    log.info('Split → train=%d  test=%d',
             (df.split=='train').sum(), (df.split=='test').sum())
    return df

# ── Step 3: Decode MP3 ────────────────────────────────────────────────────────
def decode_mp3(path):
    audio = AudioSegment.from_mp3(path)
    audio = audio.set_channels(1).set_frame_rate(SAMPLE_RATE)
    samples = np.array(audio.get_array_of_samples(), dtype=np.float32)
    samples /= np.iinfo(audio.array_type).max
    return samples

# ── Step 4: Background noise reduction ───────────────────────────────────────
def reduce_noise(y):
    """
    Spectral subtraction using the first 0.5 s as noise profile.
    prop_decrease=0.75 is conservative — avoids over-suppressing speech.
    All speech content including pauses is preserved.
    """
    noise_len  = int(NOISE_PROFILE_S * SAMPLE_RATE)
    noise_clip = y[:noise_len] if len(y) > noise_len else y
    y_clean = nr.reduce_noise(
        y=y, sr=SAMPLE_RATE,
        y_noise=noise_clip,
        stationary=False,
        prop_decrease=0.75,
    )
    return y_clean.astype(np.float32)

# ── Step 5: Edge-only silence trim ────────────────────────────────────────────
def trim_edges_only(y):
    """
    Removes silence ONLY at the very start and end of the file.
    Mid-speech pauses are NOT touched — they are critical AD biomarkers:
      - AD patients pause more frequently
      - Longer pauses indicate word-finding difficulty
      - Pause-to-speech ratio correlates with MMSE score
    librosa.effects.trim() returns (trimmed_audio, (start_sample, end_sample))
    We use the indices to slice the original array — nothing inside is changed.
    """
    _, (start, end) = librosa.effects.trim(y, top_db=EDGE_TRIM_TOP_DB)
    return y[start:end]

# ── Step 6: Peak normalisation ────────────────────────────────────────────────
def peak_normalise(y):
    peak = np.max(np.abs(y))
    return (y / peak * 0.99).astype(np.float32) if peak > 0 else y

# ── Step 7: Process one file ──────────────────────────────────────────────────
def process_one(row, stats):
    out_dir  = OUTPUT_DIR / row['split'] / row['label_str']
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / (row['subject_id'] + '.wav')

    try:
        y = decode_mp3(row['raw_path'])
        y = reduce_noise(y)
        y = trim_edges_only(y)          # internal pauses preserved

        duration_s = len(y) / SAMPLE_RATE
        if duration_s < MIN_DURATION_S:
            log.warning('Skip %s — too short (%.2fs)', row['subject_id'], duration_s)
            stats['skipped'] += 1
            return {'wav_path': '', 'duration_s': round(duration_s,3), 'status': 'skipped'}

        y = peak_normalise(y)
        sf.write(str(out_path), y, SAMPLE_RATE, subtype='PCM_16')
        stats['ok'] += 1
        return {'wav_path': str(out_path), 'duration_s': round(duration_s,3), 'status': 'ok'}

    except Exception as exc:
        log.error('Failed %s: %s', row['subject_id'], exc)
        stats['failed'] += 1
        return {'wav_path': '', 'duration_s': 0.0, 'status': f'error:{exc}'}

# ── Run preprocessing ─────────────────────────────────────────────────────────
print('=' * 55)
print('  PREPROCESSING')
print('=' * 55)

df     = discover_files(INPUT_DIR)
# Added a check here to exit if no files are found
if df.empty:
    log.error("No audio files were found. Please ensure the DATASET_PATH is correct and contains 'Dementia' and 'Control' subfolders with MP3 files.")
    print('\nPreprocessing skipped due to no audio files found.')
    # Create an empty manifest with expected columns to prevent further errors if the script continues
    df = pd.DataFrame(columns=['subject_id', 'raw_path', 'label_str', 'label', 'split', 'wav_path', 'duration_s', 'status'])
    df.to_csv(MANIFEST_OUT, index=False)
    print(f'Manifest  → {MANIFEST_OUT} (empty)')
else:
    df     = stratified_split(df)
    stats  = {'ok': 0, 'skipped': 0, 'failed': 0}
    results = []

    for _, row in tqdm(df.iterrows(), total=len(df), desc='Preprocessing'):
        results.append(process_one(row, stats))

    result_df = pd.DataFrame(results)
    df = pd.concat([df.reset_index(drop=True), result_df], axis=1)
    df.to_csv(MANIFEST_OUT, index=False)

    print(f'\nDone  ok={stats["ok"]}  skipped={stats["skipped"]}  failed={stats["failed"]}')
    print(f'Manifest  → {MANIFEST_OUT}')
    print(f'Audio dir → {OUTPUT_DIR}')
    # Only try to group by if df is not empty and has the status column
    if not df.empty and 'status' in df.columns:
        print(df[df.status=='ok'].groupby(['split','label_str']).size().rename('count').reset_index().to_string(index=False))
    else:
        print('\nNo successful audio processing records to summarize.')

"""## Cell 3 — Feature Extraction

Extracts **8 feature groups** from every cleaned WAV and saves a single `.npz` per subject.

| Group | Description | # Features |
|---|---|---|
| A | Prosodic — F0 stats, jitter, shimmer, speaking rate | 18 |
| B | MFCC + spectral — 40 MFCCs + Δ + ΔΔ, centroid, ZCR, chroma | 189 |
| C | Pause — count, mean/max dur, rate/min, pause-to-speech ratio | 8 |
| D | Voice quality — HNR, NHR, GNE, breathiness (Praat) | 6 |
| E | Articulation — F1–F3 formants, VSA, FCR, VAI (Praat) | 10 |
| F | Temporal dynamics — speech/silence run stats, switch rate | 8 |
| G | Disfluency proxies — ZCR bursts, repetition index | 4 |
| H | Wav2Vec2 — 768-d mean-pooled deep speech embedding | 768 |
| | **Total** | **1011** |
"""

import json
import torch
import torchaudio
from transformers import Wav2Vec2Model, Wav2Vec2FeatureExtractor

try:
    import parselmouth
    from parselmouth.praat import call as praat_call
    import tempfile
    PRAAT_OK = True
    print('Praat (parselmouth) available — voice quality + formant features enabled.')
except ImportError:
    PRAAT_OK = False
    print('parselmouth not found — Groups D and E will be zeros (install: pip install praat-parselmouth).')

# ── Paths ─────────────────────────────────────────────────────────────────────
FEAT_OUTPUT_DIR  = Path('/content/features')
FEAT_MANIFEST    = Path('/content/feature_manifest.csv')
FEAT_GROUPS_FILE = Path('/content/feature_groups.json')

# ── Config ────────────────────────────────────────────────────────────────────
HOP_LENGTH    = 160    # 10 ms at 16 kHz
WIN_LENGTH    = 400    # 25 ms at 16 kHz
N_MFCC        = 40
N_FFT         = 512
F0_MIN        = 60.0
F0_MAX        = 400.0
MIN_PAUSE_S   = 0.150  # minimum event counted as a pause
PAUSE_DB      = -45    # dBFS silence threshold
WAV2VEC_MODEL = 'facebook/wav2vec2-base'
DEVICE        = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {DEVICE}')

# ─────────────────────────────────────────────────────────────────────────────
# AUDIO LOADER
# ─────────────────────────────────────────────────────────────────────────────
def load_wav(path):
    y, sr = sf.read(str(path), dtype='float32')
    if y.ndim > 1:
        y = y.mean(axis=1)
    if sr != SAMPLE_RATE:
        y = librosa.resample(y, orig_sr=sr, target_sr=SAMPLE_RATE)
    return y

# ─────────────────────────────────────────────────────────────────────────────
# GROUP A — PROSODIC FEATURES  (18)
# ─────────────────────────────────────────────────────────────────────────────
def group_a_prosodic(y):
    """
    Pitch (F0) via PYIN, jitter, shimmer, RMS energy statistics,
    voiced ratio, speaking rate, rhythm.

    AD markers: reduced F0 range (monotone speech), higher jitter/shimmer
    (vocal fold instability), slower speaking rate.
    """
    feats = []
    f0, voiced_flag, _ = librosa.pyin(y, fmin=F0_MIN, fmax=F0_MAX,
                                       sr=SAMPLE_RATE, hop_length=HOP_LENGTH)
    voiced_f0 = f0[voiced_flag & ~np.isnan(f0)]

    if len(voiced_f0) > 1:
        feats += [
            float(np.mean(voiced_f0)),
            float(np.std(voiced_f0)),
            float(np.max(voiced_f0) - np.min(voiced_f0)),
            float(np.median(voiced_f0)),
            float(np.percentile(voiced_f0,75) - np.percentile(voiced_f0,25)),
            float(np.mean(np.abs(np.diff(voiced_f0))) / (np.mean(voiced_f0)+1e-9)),  # jitter
        ]
    else:
        feats += [0.0] * 6

    rms = librosa.feature.rms(y=y, frame_length=WIN_LENGTH, hop_length=HOP_LENGTH)[0]
    feats += [
        float(np.mean(rms)), float(np.std(rms)),
        float(np.max(rms)),  float(np.max(rms)-np.min(rms)),
    ]

    # Shimmer — amplitude variation between consecutive voiced frames
    vf_len     = min(len(voiced_flag), len(rms))
    voiced_rms = rms[:vf_len][voiced_flag[:vf_len]]
    shimmer    = float(np.mean(np.abs(np.diff(voiced_rms))) / (np.mean(voiced_rms)+1e-9)) if len(voiced_rms)>1 else 0.0
    feats.append(shimmer)

    duration     = len(y) / SAMPLE_RATE
    voiced_ratio = float(voiced_flag.sum() / max(len(voiced_flag),1))
    speak_rate   = float(voiced_flag.sum() * HOP_LENGTH / SAMPLE_RATE / max(duration,1e-9))
    feats += [voiced_ratio, speak_rate]

    # Rhythm — std and mean of voiced run lengths
    runs, in_run, run_len = [], False, 0
    for v in voiced_flag:
        if v:  in_run, run_len = True, run_len+1
        elif in_run: runs.append(run_len); in_run, run_len = False, 0
    feats += [float(np.mean(runs)) if runs else 0.0,
              float(np.std(runs))  if runs else 0.0]

    return np.array(feats, dtype=np.float32)   # 18

# ─────────────────────────────────────────────────────────────────────────────
# GROUP B — MFCC + SPECTRAL  (189)
# ─────────────────────────────────────────────────────────────────────────────
def group_b_mfcc_spectral(y):
    """
    40 MFCCs (mean+std) + delta (mean) + delta-delta (mean) = 160
    Spectral centroid, bandwidth, rolloff, flatness, ZCR (mean+std each) = 10
    Chroma (12 mean) + Spectral contrast (7 mean) = 19
    Total = 189

    AD markers: altered spectral envelope, reduced high-frequency energy,
    changes in formant-related MFCC patterns.
    """
    mfcc        = librosa.feature.mfcc(y=y, sr=SAMPLE_RATE, n_mfcc=N_MFCC,
                                        n_fft=N_FFT, hop_length=HOP_LENGTH,
                                        win_length=WIN_LENGTH)
    mfcc_d      = librosa.feature.delta(mfcc)
    mfcc_d2     = librosa.feature.delta(mfcc, order=2)
    mfcc_vec    = np.concatenate([
        np.mean(mfcc, axis=1), np.std(mfcc, axis=1),   # 80
        np.mean(mfcc_d,  axis=1),                       # 40
        np.mean(mfcc_d2, axis=1),                       # 40
    ])   # 160

    spec_centroid  = librosa.feature.spectral_centroid(y=y,  sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH)[0]
    spec_bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH)[0]
    spec_rolloff   = librosa.feature.spectral_rolloff(y=y,   sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH)[0]
    spec_flatness  = librosa.feature.spectral_flatness(y=y,  n_fft=N_FFT, hop_length=HOP_LENGTH)[0]
    zcr            = librosa.feature.zero_crossing_rate(y, hop_length=HOP_LENGTH)[0]
    chroma         = librosa.feature.chroma_stft(y=y, sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH)
    contrast       = librosa.feature.spectral_contrast(y=y, sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH)

    spec_vec = np.array([
        np.mean(spec_centroid),  np.std(spec_centroid),
        np.mean(spec_bandwidth), np.std(spec_bandwidth),
        np.mean(spec_rolloff),   np.std(spec_rolloff),
        np.mean(spec_flatness),  np.std(spec_flatness),
        np.mean(zcr),            np.std(zcr),
        *np.mean(chroma, axis=1),    # 12
        *np.mean(contrast, axis=1),  # 7
    ], dtype=np.float32)   # 29

    return np.concatenate([mfcc_vec, spec_vec]).astype(np.float32)   # 189

# ─────────────────────────────────────────────────────────────────────────────
# GROUP C — PAUSE FEATURES  (8)
# ─────────────────────────────────────────────────────────────────────────────
def group_c_pause(y):
    """
    Frame-level RMS energy → dBFS → silence regions → pause events >= 150 ms.
    Internal pauses are intact in the WAV because preprocess_audio only
    trimmed edge silence.

    AD markers: more pauses, longer pauses, higher pause-to-speech ratio,
    pauses at syntactically unexpected positions.
    """
    total_dur = len(y) / SAMPLE_RATE
    rms   = librosa.feature.rms(y=y, frame_length=WIN_LENGTH, hop_length=HOP_LENGTH)[0]
    db    = librosa.amplitude_to_db(rms, ref=np.max(rms+1e-9))
    times = librosa.frames_to_time(np.arange(len(db)), sr=SAMPLE_RATE, hop_length=HOP_LENGTH)

    pause_events, in_pause, p_start = [], False, 0.0
    for t, sil in zip(times, db < PAUSE_DB):
        if sil and not in_pause:
            in_pause, p_start = True, float(t)
        elif not sil and in_pause:
            in_pause = False
            dur = float(t) - p_start
            if dur >= MIN_PAUSE_S:
                pause_events.append(dur)
    if in_pause:
        dur = float(times[-1]) - p_start
        if dur >= MIN_PAUSE_S: pause_events.append(dur)

    n         = len(pause_events)
    tot_pause = sum(pause_events)
    speech_t  = max(total_dur - tot_pause, 0.0)

    return np.array([
        float(n),
        tot_pause,
        float(np.mean(pause_events)) if n > 0 else 0.0,
        float(np.max(pause_events))  if n > 0 else 0.0,
        float(n / (total_dur/60.0))  if total_dur > 0 else 0.0,
        float(tot_pause / speech_t)  if speech_t  > 0 else 0.0,
        speech_t, total_dur,
    ], dtype=np.float32)   # 8

# ─────────────────────────────────────────────────────────────────────────────
# GROUP D — VOICE QUALITY  (6)  [requires Praat]
# ─────────────────────────────────────────────────────────────────────────────
def group_d_voice_quality(y):
    """
    HNR  — Harmonics-to-Noise Ratio
    NHR  — Noise-to-Harmonics Ratio
    Jitter (local) and Shimmer (local) via Praat — more accurate than librosa
    GNE approximation — glottal noise ratio
    Breathiness index

    AD markers: reduced HNR, increased breathiness, irregular glottal pulses.
    """
    if not PRAAT_OK:
        return np.zeros(6, dtype=np.float32)
    try:
        with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp:
            tmp_path = tmp.name
        sf.write(tmp_path, y, SAMPLE_RATE, subtype='PCM_16')
        snd    = parselmouth.Sound(tmp_path)
        harm   = praat_call(snd, 'To Harmonicity (cc)', 0.01, 75, 0.1, 1.0)
        hnr    = float(praat_call(harm, 'Get mean', 0, 0))
        hnr    = hnr if not np.isnan(hnr) else 0.0
        nhr    = 1.0 / (hnr + 1e-9) if hnr > 0 else 0.0
        pp     = praat_call(snd, 'To PointProcess (periodic, cc)', F0_MIN, F0_MAX)
        jitter = float(praat_call(pp, 'Get jitter (local)', 0,0, 0.0001, 0.02, 1.3))
        shimmer= float(praat_call([snd,pp], 'Get shimmer (local)', 0,0, 0.0001, 0.02, 1.3, 1.6))
        jitter  = jitter  if not np.isnan(jitter)  else 0.0
        shimmer = shimmer if not np.isnan(shimmer) else 0.0
        S       = np.abs(librosa.stft(y, n_fft=N_FFT, hop_length=HOP_LENGTH))
        freqs   = librosa.fft_frequencies(sr=SAMPLE_RATE, n_fft=N_FFT)
        gne     = float(S[freqs>1000].mean() / (S.mean()+1e-9))
        breath  = float(np.std(y) / (np.max(np.abs(y))+1e-9))
        import os; os.unlink(tmp_path)
        return np.array([hnr, nhr, jitter, shimmer, gne, breath], dtype=np.float32)
    except Exception as e:
        log.debug('Voice quality failed: %s', e)
        return np.zeros(6, dtype=np.float32)

# ─────────────────────────────────────────────────────────────────────────────
# GROUP E — ARTICULATION / FORMANTS  (10)  [requires Praat]
# ─────────────────────────────────────────────────────────────────────────────
def group_e_articulation(y):
    """
    F1, F2, F3 mean + std, Vowel Space Area (VSA),
    Formant Centralization Ratio (FCR), Vowel Articulation Index (VAI),
    F1/F2 ratio.

    AD markers: reduced vowel space area (less precise articulation),
    higher FCR (vowel centralisation), lower VAI.
    """
    if not PRAAT_OK:
        return np.zeros(10, dtype=np.float32)
    try:
        with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp:
            tmp_path = tmp.name
        sf.write(tmp_path, y, SAMPLE_RATE, subtype='PCM_16')
        snd     = parselmouth.Sound(tmp_path)
        formant = praat_call(snd, 'To Formant (burg)', 0.0, 5, 5500, 0.025, 50)
        n_frames= int(praat_call(formant, 'Get number of frames'))
        f1v, f2v, f3v = [], [], []
        for i in range(1, n_frames+1):
            t  = praat_call(formant, 'Get time from frame number', i)
            f1 = praat_call(formant, 'Get value at time', 1, t, 'Hertz', 'Linear')
            f2 = praat_call(formant, 'Get value at time', 2, t, 'Hertz', 'Linear')
            f3 = praat_call(formant, 'Get value at time', 3, t, 'Hertz', 'Linear')
            if not any(np.isnan([f1,f2,f3])):
                f1v.append(f1); f2v.append(f2); f3v.append(f3)
        import os; os.unlink(tmp_path)
        if f1v:
            mf1,sf1 = float(np.mean(f1v)), float(np.std(f1v))
            mf2,sf2 = float(np.mean(f2v)), float(np.std(f2v))
            mf3,sf3 = float(np.mean(f3v)), float(np.std(f3v))
            vsa = float((mf2-mf1)*sf1)
            fcr = float((mf2+mf1)/(mf2+sf2+1e-9))
            vai = float(mf2/(mf1+sf1+1e-9))
            f1f2= float(np.mean(np.array(f1v)/np.array(f2v)))
            return np.array([mf1,sf1,mf2,sf2,mf3,sf3,vsa,fcr,vai,f1f2], dtype=np.float32)
        return np.zeros(10, dtype=np.float32)
    except Exception as e:
        log.debug('Articulation failed: %s', e)
        return np.zeros(10, dtype=np.float32)

# ─────────────────────────────────────────────────────────────────────────────
# GROUP F — TEMPORAL DYNAMICS  (8)
# ─────────────────────────────────────────────────────────────────────────────
def group_f_temporal(y):
    """
    Speech and silence run statistics, speech-silence switch rate.

    AD markers: longer/more variable utterances, irregular speech-silence
    alternation, slower overall communication tempo.
    """
    total_dur = len(y) / SAMPLE_RATE
    rms       = librosa.feature.rms(y=y, frame_length=WIN_LENGTH, hop_length=HOP_LENGTH)[0]
    voiced    = rms > np.mean(rms) * 0.5
    sp_runs, si_runs, in_sp, run = [], [], False, 0
    for v in voiced:
        if v:
            if not in_sp and run>0: si_runs.append(run*HOP_LENGTH/SAMPLE_RATE); run=0
            in_sp, run = True, run+1
        else:
            if in_sp and run>0: sp_runs.append(run*HOP_LENGTH/SAMPLE_RATE); run=0
            in_sp, run = False, run+1
    n_sw = float(len(sp_runs)+len(si_runs))
    return np.array([
        float(np.mean(sp_runs)) if sp_runs else 0.0,
        float(np.std(sp_runs))  if sp_runs else 0.0,
        float(np.mean(si_runs)) if si_runs else 0.0,
        float(np.std(si_runs))  if si_runs else 0.0,
        n_sw,
        float(n_sw / max(total_dur,1e-9)),
        sum(sp_runs), sum(si_runs),
    ], dtype=np.float32)   # 8

# ─────────────────────────────────────────────────────────────────────────────
# GROUP G — DISFLUENCY PROXIES  (4)
# ─────────────────────────────────────────────────────────────────────────────
def group_g_disfluency(y):
    """
    Audio-only proxies for disfluency (exact counts require transcript):
      ZCR bursts       — correlates with fricative/filler phoneme bursts
      Energy bursts    — sudden onsets → filler word starts
      Repetition proxy — short-lag MFCC autocorrelation peak
      Spectral irreg.  — abrupt spectral changes = restarts/corrections

    AD markers: more uh/um fillers, repetitions, self-corrections.
    """
    zcr      = librosa.feature.zero_crossing_rate(y, hop_length=HOP_LENGTH)[0]
    zcr_thr  = np.mean(zcr) + 2*np.std(zcr)
    zcr_b    = float(np.sum(zcr > zcr_thr))

    rms      = librosa.feature.rms(y=y, frame_length=WIN_LENGTH, hop_length=HOP_LENGTH)[0]
    rms_diff = np.diff(rms)
    e_thr    = np.mean(rms_diff) + 2*np.std(rms_diff)
    e_bursts = float(np.sum(rms_diff > e_thr))

    mfcc1    = librosa.feature.mfcc(y=y, sr=SAMPLE_RATE, n_mfcc=1,
                                     n_fft=N_FFT, hop_length=HOP_LENGTH)[0]
    if len(mfcc1) > 30:
        ac   = np.correlate(mfcc1-mfcc1.mean(), mfcc1-mfcc1.mean(), mode='full')
        ac   = ac[len(ac)//2:]; ac /= (ac[0]+1e-9)
        rep  = float(np.max(ac[5:30]))
    else:
        rep  = 0.0

    S        = np.abs(librosa.stft(y, n_fft=N_FFT, hop_length=HOP_LENGTH))
    flux     = np.sqrt(np.sum(np.diff(S, axis=1)**2, axis=0))
    sp_irr   = float(np.std(flux) / (np.mean(flux)+1e-9))

    return np.array([zcr_b, e_bursts, rep, sp_irr], dtype=np.float32)   # 4

# ─────────────────────────────────────────────────────────────────────────────
# GROUP H — WAV2VEC2 EMBEDDINGS  (768)
# ─────────────────────────────────────────────────────────────────────────────
class Wav2Vec2Embedder:
    """Loads model once, extracts mean-pooled 768-d embeddings."""
    def __init__(self):
        log.info('Loading Wav2Vec2 on %s...', DEVICE)
        self.fe    = Wav2Vec2FeatureExtractor.from_pretrained(WAV2VEC_MODEL)
        self.model = Wav2Vec2Model.from_pretrained(WAV2VEC_MODEL).to(DEVICE)
        self.model.eval()
        for p in self.model.parameters(): p.requires_grad = False
        log.info('Wav2Vec2 ready.')

    @torch.no_grad()
    def embed(self, y):
        inp = self.fe(y, sampling_rate=SAMPLE_RATE, return_tensors='pt', padding=False)
        out = self.model(inp.input_values.to(DEVICE))
        return out.last_hidden_state.mean(dim=1).squeeze(0).cpu().numpy().astype(np.float32)  # 768

# ─────────────────────────────────────────────────────────────────────────────
# CONCATENATE ALL GROUPS
# ─────────────────────────────────────────────────────────────────────────────
def extract_all(y, embedder):
    parts, groups = [], {}
    def add(name, vec):
        start = sum(len(p) for p in parts)
        parts.append(vec)
        groups[name] = {'start': start, 'end': start+len(vec), 'size': len(vec)}
    add('A_prosodic',     group_a_prosodic(y))
    add('B_mfcc',         group_b_mfcc_spectral(y))
    add('C_pause',        group_c_pause(y))
    add('D_voice',        group_d_voice_quality(y))
    add('E_articulation', group_e_articulation(y))
    add('F_temporal',     group_f_temporal(y))
    add('G_disfluency',   group_g_disfluency(y))
    add('H_wav2vec2',     embedder.embed(y))
    return np.concatenate(parts).astype(np.float32), groups

print('All feature extraction functions defined.')

# ── Run feature extraction ────────────────────────────────────────────────────
print('=' * 55)
print('  FEATURE EXTRACTION')
print('=' * 55)

manifest  = pd.read_csv(MANIFEST_OUT)
manifest  = manifest[manifest['status'] == 'ok'].reset_index(drop=True)
print(f'Files to process: {len(manifest)}')

embedder   = Wav2Vec2Embedder()
stats      = {'ok': 0, 'failed': 0}
feat_rows  = []
group_info = None

for _, row in tqdm(manifest.iterrows(), total=len(manifest), desc='Features'):
    wav_path = Path(row['wav_path'])
    out_dir  = FEAT_OUTPUT_DIR / row['split'] / row['label_str']
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / (row['subject_id'] + '.npz')

    try:
        y           = load_wav(wav_path)
        feat_vec, grp = extract_all(y, embedder)

        if group_info is None:
            group_info = grp
            print(f'\nFeature vector size: {len(feat_vec)}')
            for g, info in grp.items():
                print(f'  {g:22s}  {info["size"]:4d} features  (idx {info["start"]}:{info["end"]})')
            print()

        np.savez_compressed(str(out_path),
                            features=feat_vec,
                            label=np.array(row['label']))
        stats['ok'] += 1
        feat_rows.append({
            'subject_id':   row['subject_id'],
            'label':        row['label'],
            'label_str':    row['label_str'],
            'split':        row['split'],
            'feature_path': str(out_path),
            'n_features':   len(feat_vec),
            'status':       'ok',
        })

    except Exception as exc:
        log.error('Failed %s: %s', row['subject_id'], exc)
        stats['failed'] += 1
        feat_rows.append({
            'subject_id':   row['subject_id'],
            'label':        row['label'],
            'label_str':    row['label_str'],
            'split':        row['split'],
            'feature_path': '',
            'n_features':   0,
            'status':       f'error:{exc}',
        })

feat_manifest = pd.DataFrame(feat_rows)
feat_manifest.to_csv(FEAT_MANIFEST, index=False)

if group_info:
    with open(FEAT_GROUPS_FILE, 'w') as fh:
        json.dump(group_info, fh, indent=2)

print(f'\nDone  ok={stats["ok"]}  failed={stats["failed"]}')
print(f'Feature manifest → {FEAT_MANIFEST}')
print(f'Group info       → {FEAT_GROUPS_FILE}')

"""## Cell 4 — Verify Outputs + Summary Stats"""

import matplotlib.pyplot as plt

fm = pd.read_csv(FEAT_MANIFEST)
ok = fm[fm['status'] == 'ok']

print('=== Output summary ===')
print(ok.groupby(['split','label_str']).size().rename('count').reset_index().to_string(index=False))

print(f'\nTotal features per subject : {ok["n_features"].iloc[0]}')
print('\nFeature group breakdown:')
with open(FEAT_GROUPS_FILE) as fh:
    gi = json.load(fh)
for g, info in gi.items():
    print(f'  {g:22s}  {info["size"]:4d}  (idx {info["start"]}:{info["end"]})')

# Quick sanity check — load one sample from each class
print('\n=== Sanity check (first sample from each class) ===')
for label_str in ['Dementia', 'Control']:
    row   = ok[ok['label_str'] == label_str].iloc[0]
    data  = np.load(row['feature_path'])
    feats = data['features']
    print(f'  {label_str:10s}  shape={feats.shape}  '
          f'mean={feats.mean():.4f}  std={feats.std():.4f}  '
          f'nan={np.isnan(feats).sum()}  inf={np.isinf(feats).sum()}')

# Optionally copy outputs to Drive for persistence
print('\n=== Copying outputs to Google Drive ===')
import shutil
DRIVE_OUT = Path('/content/drive/MyDrive/pitt_outputs')
DRIVE_OUT.mkdir(parents=True, exist_ok=True)

shutil.copy(FEAT_MANIFEST,    DRIVE_OUT / 'feature_manifest.csv')
shutil.copy(FEAT_GROUPS_FILE, DRIVE_OUT / 'feature_groups.json')
shutil.copy(MANIFEST_OUT,     DRIVE_OUT / 'audio_manifest.csv')

# Copy feature .npz files
feat_drive = DRIVE_OUT / 'features'
if feat_drive.exists(): shutil.rmtree(feat_drive)
shutil.copytree(FEAT_OUTPUT_DIR, feat_drive)

print(f'All outputs saved to {DRIVE_OUT}')
print('Next step: run train_wav2vec2.py using feature_manifest.csv')