# -*- coding: utf-8 -*-
"""transcript_preprocess_and_extract (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeQinhSHCUcIwcUw3vYIRqJcrYdNG2II

# Pitt Corpus — Transcript Preprocessing + Feature Extraction
## Using DistilRoBERTa embeddings

**Input:** `/content/drive/MyDrive/pitt_corpus/Dementia/*.cha` and `Control/*.cha`

```
CELL 1 — Mount Drive + Install packages
CELL 2 — Parse .cha files
         Extract *PAR: turns only · strip all CHAT codes
         Log pause markers as separate JSON
         → processed_transcripts/ + transcript_manifest.csv
CELL 3 — Feature extraction (8 groups, 880 features total)
         A. Lexical richness   — TTR, MATTR, Brunet W, Honoré R        (8)
         B. Syntactic          — MLU, POS ratios, dependency arc length (10)
         C. Semantic           — content density, filler rate, entity   (6)
         D. Pause/disfluency   — count, duration, rate from .cha codes  (10)
         E. Discourse          — repetition, informativeness, coherence  (8)
         F. Sentiment/affect   — polarity, uncertainty, hedge density   (6)
         G. Readability        — Flesch, SMOG, avg word/sentence length (8)
         H. DistilRoBERTa      — 768-d CLS embedding (distilroberta-base)(768)
         → transcript_features/ + transcript_feature_manifest.csv
CELL 4 — Verify outputs + Save to Drive
```

**Why DistilRoBERTa over BERT?**
- 40% fewer parameters than RoBERTa-base, 60% faster inference
- Trained with RoBERTa's dynamic masking (better than BERT's static)
- Same 768-d hidden size — identical downstream compatibility
- Better suited for short, fragmented speech transcripts

> Same `random_state=42` split as audio notebook — subject IDs align.

## Cell 1 — Mount Drive + Install Packages
"""

from google.colab import drive
drive.mount('/content/drive')

import os
DATASET_PATH = '/content/drive/MyDrive/pitt_corpus/transcripts'
for cls in ['Dementia', 'Control']:
    folder = os.path.join(DATASET_PATH, cls)
    if os.path.exists(folder):
        n = len([f for f in os.listdir(folder) if f.endswith('.cha')])
        print(f'  {cls}: {n} .cha files found')
    else:
        print(f'  WARNING: {folder} not found')

!cd /content/drive/MyDrive/pitt_corpus/

!pip install -q transformers torch spacy textstat nltk textblob
!python -m spacy download en_core_web_sm -q

import nltk
nltk.download('punkt',                      quiet=True)
nltk.download('punkt_tab',                  quiet=True)
nltk.download('stopwords',                  quiet=True)
nltk.download('averaged_perceptron_tagger', quiet=True)
nltk.download('averaged_perceptron_tagger_eng', quiet=True)
print('All packages ready.')

"""## Cell 2 — Parse .cha Files

Extracts `*PAR:` (participant) turns, strips all CHAT annotation codes,  
and saves pause markers separately for Group D feature extraction.
"""

import re, json, logging, warnings
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

warnings.filterwarnings('ignore')
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s | %(levelname)-8s | %(message)s',
                    datefmt='%H:%M:%S')
log = logging.getLogger(__name__)

# ── Paths ─────────────────────────────────────────────────────────────────────
INPUT_DIR   = Path('/content/drive/MyDrive/pitt_corpus/transcripts')
OUTPUT_DIR  = Path('/content/drive/MyDrive/processed_transcripts')
MANIFEST    = Path('/content/drive/MyDrive/transcript_manifest.csv')

PARTICIPANT_CODE = 'PAR'
TEST_SIZE        = 0.20
RANDOM_STATE     = 42
LABEL_MAP        = {'Dementia': 1, 'Control': 0}

# ── CHAT code regex patterns ───────────────────────────────────────────────────
_RE_RETRACING  = re.compile(r'\[//\]|\[/\]')
_RE_POSTCODES  = re.compile(r'\[[\+\-][^\]]*\]')
_RE_INLINE     = re.compile(r'\[.*?\]')
_RE_ANGLE      = re.compile(r'<[^>]*>')
_RE_NONWORD    = re.compile(r'&[=+\-]?\w+')
_RE_PAUSE_NUM  = re.compile(r'\((\d+\.\d+)\)')    # (1.5)
_RE_PAUSE_DOT  = re.compile(r'\(\.{1,3}\)')        # (.) (..) (...)
_RE_TIMING     = re.compile(r'\d+_\d+')
_RE_UNINTEL    = re.compile(r'\b(xxx|yyy|www)\b', re.IGNORECASE)
_RE_SCOPE      = re.compile(r'[+/\\<>]')
_RE_PROSODY    = re.compile(r'[↑↓⇗⇘∞≈≋≡○●⌊⌋⌈⌉]')
_RE_MULTISPC   = re.compile(r' {2,}')
_RE_SPEAKER    = re.compile(r'^\*(\w+):\s*(.*)')


def extract_pause_markers(raw_turn):
    """Extract pause markers before stripping — returns list of pause dicts."""
    pauses = []
    for i, tok in enumerate(raw_turn.split()):
        m = _RE_PAUSE_NUM.search(tok)
        if m:
            pauses.append({'type': 'numeric', 'duration_s': float(m.group(1)), 'position': i})
        m2 = _RE_PAUSE_DOT.search(tok)
        if m2:
            dots = tok.count('.')
            pauses.append({'type': 'short', 'duration_s': dots * 0.1, 'position': i})
    return pauses


def clean_utterance(raw):
    """Strip all CHAT codes → plain lowercase text."""
    text = raw
    text = _RE_RETRACING.sub('', text)
    text = _RE_POSTCODES.sub('', text)
    text = _RE_INLINE.sub('', text)
    text = _RE_ANGLE.sub('', text)
    text = _RE_NONWORD.sub('', text)
    text = _RE_PAUSE_NUM.sub('', text)
    text = _RE_PAUSE_DOT.sub('', text)
    text = _RE_TIMING.sub('', text)
    text = _RE_UNINTEL.sub('', text)
    text = _RE_SCOPE.sub(' ', text)
    text = _RE_PROSODY.sub('', text)
    text = re.sub(r"[^a-zA-Z0-9 '.,!?]", ' ', text)
    text = _RE_MULTISPC.sub(' ', text).strip().lower()
    return text


def parse_cha(cha_path, speaker=PARTICIPANT_CODE):
    """Parse .cha → (utterances, raw_turns, all_pauses, metadata)."""
    utterances, raw_turns, all_pauses, metadata = [], [], [], {}
    current_speaker, current_turn = None, []

    def flush():
        nonlocal current_speaker, current_turn
        if current_speaker == speaker and current_turn:
            raw    = ' '.join(current_turn)
            pauses = extract_pause_markers(raw)
            for p in pauses:
                p['turn_index'] = len(utterances)
            all_pauses.extend(pauses)
            cleaned = clean_utterance(raw)
            if cleaned:
                raw_turns.append(raw.strip())
                utterances.append(cleaned)
        current_turn.clear()
        current_speaker = None

    with open(cha_path, encoding='utf-8', errors='replace') as fh:
        for line in fh:
            line = line.rstrip('\n')
            if line.startswith('@'):
                flush()
                m = re.match(r'^@(\w+):\s*(.*)', line)
                if m: metadata[m.group(1)] = m.group(2).strip()
                continue
            if line.startswith('%'):
                continue
            m = _RE_SPEAKER.match(line)
            if m:
                flush()
                current_speaker = m.group(1).upper()
                current_turn    = [m.group(2)]
                continue
            if line.startswith(('\t', ' ')) and current_speaker:
                current_turn.append(line.strip())
    flush()
    return utterances, raw_turns, all_pauses, metadata


def discover_files(input_dir):
    records = []
    for label_str in LABEL_MAP:
        folder = input_dir / label_str
        if not folder.exists():
            log.warning('Folder not found: %s', folder)
            continue
        for cha in sorted(folder.glob('*.cha')):
            records.append({'subject_id': cha.stem, 'raw_path': str(cha),
                            'label_str': label_str, 'label': LABEL_MAP[label_str]})
    df = pd.DataFrame(records)
    log.info('Found %d files  (Dem=%d  Ctrl=%d)',
             len(df), (df.label==1).sum(), (df.label==0).sum())
    return df


def stratified_split(df):
    _, test_df = train_test_split(df, test_size=TEST_SIZE,
                                  stratify=df['label'], random_state=RANDOM_STATE)
    df = df.copy()
    df['split'] = 'train'
    df.loc[test_df.index, 'split'] = 'test'
    log.info('Split → train=%d  test=%d',
             (df.split=='train').sum(), (df.split=='test').sum())
    return df


def process_one(row, stats):
    sid     = row['subject_id']
    out_dir = OUTPUT_DIR / row['split'] / row['label_str']
    out_dir.mkdir(parents=True, exist_ok=True)
    try:
        utts, raw_turns, pauses, meta = parse_cha(row['raw_path'])
        if not utts:
            stats['skipped'] += 1
            return {'clean_path': '', 'pause_path': '',
                    'n_utterances': 0, 'n_tokens': 0, 'n_pauses': 0,
                    'status': 'skipped_no_utterances'}

        full_clean = ' '.join(utts)
        n_tokens   = len(full_clean.split())

        clean_path = out_dir / f'{sid}.txt'
        clean_path.write_text(full_clean, encoding='utf-8')

        pause_data = {
            'subject_id':    sid,
            'label':         row['label'],
            'label_str':     row['label_str'],
            'split':         row['split'],
            'n_utterances':  len(utts),
            'n_pauses':      len(pauses),
            'total_pause_s': round(sum(p['duration_s'] for p in pauses), 3),
            'pause_events':  pauses,
        }
        pause_path = out_dir / f'{sid}_pauses.json'
        pause_path.write_text(json.dumps(pause_data, indent=2), encoding='utf-8')

        stats['ok'] += 1
        return {'clean_path': str(clean_path), 'pause_path': str(pause_path),
                'n_utterances': len(utts), 'n_tokens': n_tokens,
                'n_pauses': len(pauses), 'status': 'ok'}
    except Exception as exc:
        log.error('Failed %s: %s', sid, exc)
        stats['failed'] += 1
        return {'clean_path': '', 'pause_path': '',
                'n_utterances': 0, 'n_tokens': 0, 'n_pauses': 0,
                'status': f'error:{exc}'}


# ── Run preprocessing ─────────────────────────────────────────────────────────
print('=' * 55)
print('  TRANSCRIPT PREPROCESSING')
print('=' * 55)

df     = discover_files(INPUT_DIR)
df     = stratified_split(df)
stats  = {'ok': 0, 'skipped': 0, 'failed': 0}
results = []

for _, row in tqdm(df.iterrows(), total=len(df), desc='Parsing .cha'):
    results.append(process_one(row, stats))

result_df = pd.DataFrame(results)
df = pd.concat([df.reset_index(drop=True), result_df], axis=1)
df.to_csv(MANIFEST, index=False)

ok = df[df.status=='ok']
print(f'\nDone  ok={stats["ok"]}  skipped={stats["skipped"]}  failed={stats["failed"]}')
print(f'Avg tokens/subject : {ok.n_tokens.mean():.1f}')
print(f'Avg pauses/subject : {ok.n_pauses.mean():.1f}')
ok.groupby(['split','label_str']).agg(
    count=('subject_id','count'),
    avg_tokens=('n_tokens','mean'),
    avg_pauses=('n_pauses','mean')
).round(1)

"""## Cell 3 — Feature Extraction

| Group | Features | Count |
|---|---|---|
| A | Lexical richness — TTR, MATTR, Brunet W, Honoré R, hapax ratio, density | 8 |
| B | Syntactic — MLU, POS ratios, arc length, tokens/sentence | 10 |
| C | Semantic — content density, filler rate, empty phrase, entity | 6 |
| D | Pause/disfluency — count, duration, rate, numeric/short split | 10 |
| E | Discourse — repetition, bigram overlap, informativeness, coherence | 8 |
| F | Sentiment/affect — polarity, subjectivity, uncertainty, hedge | 6 |
| G | Readability — Flesch, SMOG, Fog, avg word/sent length, syllables | 8 |
| H | **DistilRoBERTa** — 768-d CLS token from `distilroberta-base` | 768 |
| | **Total** | **824** |
"""

import torch
import spacy
import textstat
from collections import Counter
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from textblob import TextBlob
from transformers import AutoTokenizer, AutoModel

nlp        = spacy.load('en_core_web_sm')
STOP_WORDS = set(stopwords.words('english'))
DEVICE     = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {DEVICE}')

# ── Output paths ──────────────────────────────────────────────────────────────
FEAT_OUTPUT_DIR  = Path('/content/transcript_features')
FEAT_MANIFEST    = Path('/content/transcript_feature_manifest.csv')
FEAT_GROUPS_FILE = Path('/content/transcript_feature_groups.json')

# ── DistilRoBERTa model name ───────────────────────────────────────────────────
DISTILROBERTA_MODEL = 'distilroberta-base'


# ─────────────────────────────────────────────────────────────────────────────
# GROUP A — LEXICAL RICHNESS  (8)
# AD markers: reduced TTR (repetitive vocabulary), fewer hapax legomena,
# lower lexical density (more function words, fewer content words)
# ─────────────────────────────────────────────────────────────────────────────
def group_a_lexical(text):
    tokens = word_tokenize(text.lower())
    words  = [t for t in tokens if t.isalpha()]
    if not words:
        return np.zeros(8, dtype=np.float32)
    N, V   = len(words), len(set(words))
    ttr    = V / N

    # MATTR — moving average TTR (window=25, corrects for length sensitivity)
    win    = 25
    mattr  = float(np.mean([len(set(words[i:i+win]))/win
                             for i in range(N-win+1)])) if N >= win else ttr

    # Brunet's W — lower = richer vocabulary
    brunet = float(N ** (V ** -0.165)) if V > 0 else 0.0

    # Honoré's R
    freq   = Counter(words)
    hapax  = sum(1 for c in freq.values() if c == 1)
    honore = float(100 * np.log(N) / (1 - hapax/V)) if (V > hapax and N > 1) else 0.0
    hapax_ratio = hapax / V if V > 0 else 0.0

    # Lexical density (content words / all words)
    doc         = nlp(text[:5000])
    content_pos = {'NOUN','VERB','ADJ','ADV'}
    content_n   = sum(1 for t in doc if t.pos_ in content_pos and t.is_alpha)
    lex_density = content_n / max(sum(1 for t in doc if t.is_alpha), 1)

    return np.array([ttr, mattr, brunet, honore, float(N), float(V),
                     hapax_ratio, lex_density], dtype=np.float32)  # 8


# ─────────────────────────────────────────────────────────────────────────────
# GROUP B — SYNTACTIC FEATURES  (10)
# AD markers: shorter MLU, simpler grammar, higher pronoun-noun ratio
# (vague reference instead of naming objects)
# ─────────────────────────────────────────────────────────────────────────────
def group_b_syntactic(text):
    doc   = nlp(text[:8000])
    sents = list(doc.sents)
    if not sents:
        return np.zeros(10, dtype=np.float32)

    sent_lens = [len([t for t in s if t.is_alpha]) for s in sents]
    mlu       = float(np.mean(sent_lens))
    mlu_std   = float(np.std(sent_lens))

    tokens    = [t for t in doc if t.is_alpha]
    N         = max(len(tokens), 1)
    pos_count = Counter(t.pos_ for t in tokens)

    noun_r = pos_count.get('NOUN', 0) / N
    verb_r = pos_count.get('VERB', 0) / N
    pron_r = pos_count.get('PRON', 0) / N
    adj_r  = pos_count.get('ADJ',  0) / N
    adv_r  = pos_count.get('ADV',  0) / N

    # Average dependency arc length — longer = more complex syntax
    arc_lens = [abs(t.i - t.head.i) for t in doc if t.dep_ != 'ROOT']
    avg_arc  = float(np.mean(arc_lens)) if arc_lens else 0.0

    n_sents      = float(len(sents))
    tok_per_sent = float(N) / max(n_sents, 1)

    return np.array([mlu, mlu_std, n_sents, noun_r, verb_r,
                     pron_r, adj_r, adv_r, avg_arc, tok_per_sent],
                    dtype=np.float32)  # 10


# ─────────────────────────────────────────────────────────────────────────────
# GROUP C — SEMANTIC FEATURES  (6)
# AD markers: more empty speech, higher pronoun-noun ratio,
# more filler words, lower content density
# ─────────────────────────────────────────────────────────────────────────────
def group_c_semantic(text):
    doc    = nlp(text[:8000])
    tokens = [t for t in doc if t.is_alpha]
    N      = max(len(tokens), 1)

    content_pos = {'NOUN','VERB','ADJ','ADV'}
    content_den = sum(1 for t in tokens if t.pos_ in content_pos) / N

    empty_words = {'it','thing','stuff','something','anything','everything','one'}
    empty_ratio = sum(1 for t in tokens if t.lower_ in empty_words) / N

    avg_wlen    = float(np.mean([len(t.text) for t in tokens]))

    ent_ratio   = len(doc.ents) / max(len(list(doc.sents)), 1)

    nouns  = sum(1 for t in tokens if t.pos_ == 'NOUN')
    prons  = sum(1 for t in tokens if t.pos_ == 'PRON')
    pn_ratio = prons / max(nouns, 1)

    fillers  = {'uh','um','er','ah','well','like'}
    fill_r   = sum(1 for t in tokens if t.lower_ in fillers) / N

    return np.array([content_den, empty_ratio, avg_wlen,
                     float(ent_ratio), pn_ratio, fill_r],
                    dtype=np.float32)  # 6


# ─────────────────────────────────────────────────────────────────────────────
# GROUP D — PAUSE / DISFLUENCY  (10)
# Derived from the pause log saved during .cha parsing (Cell 2)
# AD markers: more pauses, longer pauses, more mid-utterance pauses
# ─────────────────────────────────────────────────────────────────────────────
def group_d_pause(pause_json_path):
    try:
        data   = json.loads(Path(pause_json_path).read_text())
        events = data.get('pause_events', [])
        n_utt  = max(data.get('n_utterances', 1), 1)
    except Exception:
        return np.zeros(10, dtype=np.float32)

    n_p     = len(events)
    durs    = [e['duration_s'] for e in events]
    tot_p   = sum(durs)
    mean_p  = float(np.mean(durs)) if durs else 0.0
    max_p   = float(np.max(durs))  if durs else 0.0
    std_p   = float(np.std(durs))  if durs else 0.0
    p_rate  = n_p / n_utt

    num_p   = sum(1 for e in events if e['type'] == 'numeric')
    short_p = sum(1 for e in events if e['type'] == 'short')
    num_r   = num_p   / max(n_p, 1)
    short_r = short_p / max(n_p, 1)

    return np.array([float(n_p), tot_p, mean_p, max_p, std_p,
                     p_rate, num_r, short_r, float(num_p), float(short_p)],
                    dtype=np.float32)  # 10


# ─────────────────────────────────────────────────────────────────────────────
# GROUP E — DISCOURSE FEATURES  (8)
# AD markers: more repetition, lower informativeness, fragmented sentences,
# less use of discourse connectives
# ─────────────────────────────────────────────────────────────────────────────
def group_e_discourse(text):
    sents  = sent_tokenize(text)
    n_s    = max(len(sents), 1)
    tokens = word_tokenize(text.lower())
    words  = [t for t in tokens if t.isalpha() and t not in STOP_WORDS]
    N      = max(len(words), 1)

    freq      = Counter(words)
    rep_ratio = sum(c-1 for c in freq.values() if c>1) / N

    def bigrams(s):
        w = word_tokenize(s.lower())
        return set(zip(w, w[1:]))
    overlaps = []
    for i in range(len(sents)-1):
        bg1, bg2 = bigrams(sents[i]), bigrams(sents[i+1])
        denom    = max(len(bg1|bg2), 1)
        overlaps.append(len(bg1&bg2) / denom)
    sent_overlap    = float(np.mean(overlaps)) if overlaps else 0.0

    informativeness = len(freq) / N
    slen_std        = float(np.std([len(word_tokenize(s)) for s in sents])) if n_s>1 else 0.0
    q_ratio         = sum(1 for s in sents if s.strip().endswith('?')) / n_s
    short_sent      = sum(1 for s in sents if len(word_tokenize(s)) < 4) / n_s

    connectives = {'and','but','so','because','then','also','however',
                   'therefore','although','while','since','when','if'}
    conn_ratio  = sum(1 for t in tokens if t in connectives) / max(len(tokens), 1)

    return np.array([rep_ratio, sent_overlap, informativeness, slen_std,
                     q_ratio, short_sent, conn_ratio, float(n_s)],
                    dtype=np.float32)  # 8


# ─────────────────────────────────────────────────────────────────────────────
# GROUP F — SENTIMENT / AFFECT  (6)
# AD markers: reduced emotional expressiveness, more uncertainty language,
# more hedging (reflects word-finding difficulty and low confidence)
# ─────────────────────────────────────────────────────────────────────────────
def group_f_sentiment(text):
    try:
        tb   = TextBlob(text)
        pol  = float(tb.sentiment.polarity)
        subj = float(tb.sentiment.subjectivity)
    except Exception:
        pol, subj = 0.0, 0.0

    tokens = word_tokenize(text.lower())
    N      = max(len(tokens), 1)

    pos_words  = {'good','nice','happy','love','beautiful','wonderful','great'}
    neg_words  = {'bad','sad','terrible','awful','hate','horrible','wrong'}
    uncertainty= {'maybe','perhaps','possibly','might','think','guess',
                  'suppose','probably','seem','appear','feel'}
    hedge_wds  = {'kind of','sort of','a bit','rather','quite','somewhat','fairly'}

    text_l = text.lower()
    pos_r  = sum(1 for t in tokens if t in pos_words)   / N
    neg_r  = sum(1 for t in tokens if t in neg_words)   / N
    unc_r  = sum(1 for t in tokens if t in uncertainty) / N
    hedge_r= sum(1 for h in hedge_wds if h in text_l) / len(hedge_wds)

    return np.array([pol, subj, pos_r, neg_r, unc_r, hedge_r],
                    dtype=np.float32)  # 6


# ─────────────────────────────────────────────────────────────────────────────
# GROUP G — READABILITY  (8)
# AD markers: simpler sentence structure, shorter words, lower grade level
# ─────────────────────────────────────────────────────────────────────────────
def group_g_readability(text):
    try:
        fre  = float(textstat.flesch_reading_ease(text))
        fkg  = float(textstat.flesch_kincaid_grade(text))
        smog = float(textstat.smog_index(text))
        fog  = float(textstat.gunning_fog(text))
    except Exception:
        fre = fkg = smog = fog = 0.0

    tokens  = [t for t in word_tokenize(text.lower()) if t.isalpha()]
    N       = max(len(tokens), 1)
    sents   = sent_tokenize(text)
    avg_wl  = float(np.mean([len(t) for t in tokens]))
    avg_sl  = float(N / max(len(sents), 1))

    def count_syl(w):
        return max(1, len(re.findall(r'[aeiouy]+', w.lower())))
    avg_syl = float(np.mean([count_syl(t) for t in tokens]))
    long_r  = sum(1 for t in tokens if len(t) > 6) / N

    return np.array([fre, fkg, smog, fog, avg_wl, avg_sl, avg_syl, long_r],
                    dtype=np.float32)  # 8


# ─────────────────────────────────────────────────────────────────────────────
# GROUP H — DistilRoBERTa EMBEDDINGS  (768)
# distilroberta-base: 82M params, 40% smaller than roberta-base,
# same 768-d hidden size, better than BERT on short/informal text
# ─────────────────────────────────────────────────────────────────────────────
class DistilRoBERTaEmbedder:
    """
    Loads distilroberta-base once.
    Returns 768-d CLS token embedding per transcript.

    Why distilroberta-base over bert-base-uncased?
    - RoBERTa training: dynamic masking, no NSP, longer training
    - 40% fewer params → faster, less VRAM pressure on Colab
    - Handles fragmented, colloquial speech transcripts better
    - Uses BPE tokenisation — better for non-standard words in AD speech
    """
    MAX_TOKENS = 512

    def __init__(self):
        log.info('Loading DistilRoBERTa on %s...', DEVICE)
        self.tokenizer = AutoTokenizer.from_pretrained(DISTILROBERTA_MODEL)
        self.model     = AutoModel.from_pretrained(DISTILROBERTA_MODEL).to(DEVICE)
        self.model.eval()
        for p in self.model.parameters(): p.requires_grad = False
        log.info('DistilRoBERTa ready.')

    @torch.no_grad()
    def embed(self, text):
        enc = self.tokenizer(
            text,
            max_length=self.MAX_TOKENS,
            truncation=True,
            padding='max_length',
            return_tensors='pt',
        )
        out = self.model(
            input_ids=enc.input_ids.to(DEVICE),
            attention_mask=enc.attention_mask.to(DEVICE),
        )
        # CLS token = first token of last hidden state
        return out.last_hidden_state[:, 0, :].squeeze(0).cpu().numpy().astype(np.float32)


# ─────────────────────────────────────────────────────────────────────────────
# COMBINE ALL GROUPS
# ─────────────────────────────────────────────────────────────────────────────
def extract_all(text, pause_path, embedder):
    parts, groups = [], {}
    def add(name, vec):
        start = sum(len(p) for p in parts)
        parts.append(vec)
        groups[name] = {'start': start, 'end': start+len(vec), 'size': len(vec)}
    add('A_lexical',       group_a_lexical(text))
    add('B_syntactic',     group_b_syntactic(text))
    add('C_semantic',      group_c_semantic(text))
    add('D_pause',         group_d_pause(pause_path))
    add('E_discourse',     group_e_discourse(text))
    add('F_sentiment',     group_f_sentiment(text))
    add('G_readability',   group_g_readability(text))
    add('H_distilroberta', embedder.embed(text))
    return np.concatenate(parts).astype(np.float32), groups


print('All feature extraction functions defined.')

# ── Run feature extraction ────────────────────────────────────────────────────
print('=' * 55)
print('  FEATURE EXTRACTION  (DistilRoBERTa)')
print('=' * 55)

manifest  = pd.read_csv(MANIFEST)
manifest  = manifest[manifest['status'] == 'ok'].reset_index(drop=True)
print(f'Files to process: {len(manifest)}')

embedder   = DistilRoBERTaEmbedder()
stats      = {'ok': 0, 'failed': 0}
feat_rows  = []
group_info = None # This will be set by the first call to process_one


def process_one(row, stats):
    global group_info # Declare as global to modify the outer group_info

    sid     = row['subject_id']
    # Use the clean_path and pause_path from the manifest generated in Cell 2
    clean_text_path = Path(row['clean_path'])
    pause_json_path = Path(row['pause_path'])

    # Define the output path for the feature .npz file
    feat_out_subject_dir = FEAT_OUTPUT_DIR / row['split'] / row['label_str']
    feat_out_subject_dir.mkdir(parents=True, exist_ok=True)
    out_path = feat_out_subject_dir / f'{sid}.npz'

    try:
        if not clean_text_path.exists() or not pause_json_path.exists():
            log.warning(f"Required files for {sid} not found. Skipping. Text: {clean_text_path}, Pause: {pause_json_path}")
            stats['failed'] += 1 # or skipped
            return {
                'subject_id': row['subject_id'], 'label': row['label'],
                'label_str':  row['label_str'],  'split': row['split'],
                'feature_path': '', 'n_features': 0, 'status': 'error:file_not_found',
            }

        text = clean_text_path.read_text(encoding='utf-8')
        feat_vec, grp = extract_all(text, str(pause_json_path), embedder)

        if group_info is None: # Set group_info only once
            group_info = grp
            print(f'\nFeature vector size: {len(feat_vec)}')
            for g_key, info_val in grp.items():
                print(f'  {g_key:22s}  {info_val["size"]:4d}  (idx {info_val["start"]}:{info_val["end"]})')
            print()

        np.savez_compressed(str(out_path),
                            features=feat_vec,
                            label=np.array(row['label']))
        stats['ok'] += 1
        return {
            'subject_id':   row['subject_id'],
            'label':        row['label'],
            'label_str':    row['label_str'],
            'split':        row['split'],
            'feature_path': str(out_path),
            'n_features':   len(feat_vec),
            'status':       'ok',
        }

    except Exception as exc:
        log.error('Failed %s: %s', row['subject_id'], exc)
        stats['failed'] += 1
        return {
            'subject_id': row['subject_id'], 'label': row['label'],
            'label_str':  row['label_str'],  'split': row['split'],
            'feature_path': '', 'n_features': 0, 'status': f'error:{exc}',
        }

# --- Add this loop to call process_one for each subject ---
for _, row in tqdm(manifest.iterrows(), total=len(manifest), desc='Extracting Features'):
    feat_rows.append(process_one(row, stats))

feat_manifest = pd.DataFrame(feat_rows)
feat_manifest.to_csv(FEAT_MANIFEST, index=False)
with open(FEAT_GROUPS_FILE, 'w') as fh:
    json.dump(group_info, fh, indent=2)

print(f'\nDone  ok={stats["ok"]}  failed={stats["failed"]}')
print(f'Feature manifest → {FEAT_MANIFEST}')
print(f'Group info       → {FEAT_GROUPS_FILE}')

"""## Cell 4 — Dataset

This `Dataset` class loads the preprocessed transcript text and the extracted hand-crafted features (Groups A-G) for each subject. It will be used in the training pipeline to prepare data for the model.

Each `__getitem__` call will load:
1. The **raw transcript text** (`.txt`) — tokenised and fed live to DistilRoBERTa
2. **Hand-crafted features A–G** from `.npz` (group H excluded — computed live)
"""

import torch
from torch.utils.data import Dataset

class TranscriptDataset(Dataset):
    def __init__(self, manifest_df, feature_groups):
        self.manifest_df    = manifest_df.reset_index(drop=True)
        self.feature_groups = feature_groups

    def __len__(self):
        return len(self.manifest_df)

    def __getitem__(self, idx):
        row         = self.manifest_df.iloc[idx]
        subject_id  = row['subject_id']
        clean_path  = row['clean_path']
        feature_path = row['feature_path']
        label       = row['label']

        # Load raw text
        text = Path(clean_path).read_text(encoding='utf-8')

        # Load features (A-G)
        all_features = np.load(feature_path)['features']

        # Exclude DistilRoBERTa features (Group H) as they will be recomputed live
        # This assumes H_distilroberta is the last group in the feature_groups dict
        h_start_idx = self.feature_groups['H_distilroberta']['start']
        hand_crafted_features = all_features[:h_start_idx]

        return {
            'subject_id': subject_id,
            'text':       text,
            'features':   torch.from_numpy(hand_crafted_features).float(),
            'label':      torch.tensor(label, dtype=torch.long)
        }

print('TranscriptDataset class defined.')

"""## Cell 4 — Verify + Save to Drive"""

import shutil, matplotlib.pyplot as plt

fm = pd.read_csv(FEAT_MANIFEST)
ok = fm[fm['status'] == 'ok']

print('=== Output summary ===')
print(ok.groupby(['split','label_str']).size().rename('count').reset_index().to_string(index=False))
print(f'\nTotal features per subject: {ok["n_features"].iloc[0]}')

print('\nFeature group breakdown:')
with open(FEAT_GROUPS_FILE) as fh:
    gi = json.load(fh)
for g, info in gi.items():
    print(f'  {g:22s}  {info["size"]:4d}  (idx {info["start"]}:{info["end"]})')

print('\n=== Sanity check ===')
for label_str in ['Dementia', 'Control']:
    row   = ok[ok['label_str'] == label_str].iloc[0]
    feats = np.load(row['feature_path'])['features']
    print(f'  {label_str:10s}  shape={feats.shape}  '
          f'mean={feats.mean():.4f}  nan={np.isnan(feats).sum()}  inf={np.isinf(feats).sum()}')

# Save to Drive
DRIVE_OUT = Path('/content/drive/MyDrive/pitt_transcript_outputs')
DRIVE_OUT.mkdir(parents=True, exist_ok=True)

for f in [FEAT_MANIFEST, FEAT_GROUPS_FILE, MANIFEST]:
    shutil.copy(f, DRIVE_OUT / Path(f).name)
    print(f'  Saved {Path(f).name}')

feat_drive = DRIVE_OUT / 'transcript_features'
if feat_drive.exists(): shutil.rmtree(feat_drive)
shutil.copytree(FEAT_OUTPUT_DIR, feat_drive)
print(f'  Saved transcript_features/')

print(f'\nAll outputs → {DRIVE_OUT}')

